<<<<<<< HEAD
# Cloudflare Pages Configuration
build:
  command: ""
  output: "."
  environment:
    NODE_VERSION: "18"

# Headers for search engine access
headers:
  - pattern: "/*"
    headers:
      - key: "X-Robots-Tag"
        value: "index, follow"
      - key: "Access-Control-Allow-Origin"
        value: "*"
      - key: "Access-Control-Allow-Methods"
        value: "GET, POST, OPTIONS"
      - key: "Access-Control-Allow-Headers"
        value: "Content-Type"

# Redirects
redirects:
  - from: "/index.html"
    to: "/"
    status: 301
  - from: "/testimonials.html"
    to: "/testimonials"
=======
# Cloudflare Pages Configuration
build:
  command: ""
  output: "."
  environment:
    NODE_VERSION: "18"

# Headers for search engine access
headers:
  - pattern: "/*"
    headers:
      - key: "X-Robots-Tag"
        value: "index, follow"
      - key: "Access-Control-Allow-Origin"
        value: "*"
      - key: "Access-Control-Allow-Methods"
        value: "GET, POST, OPTIONS"
      - key: "Access-Control-Allow-Headers"
        value: "Content-Type"

# Redirects
redirects:
  - from: "/index.html"
    to: "/"
    status: 301
  - from: "/testimonials.html"
    to: "/testimonials"
>>>>>>> 2278488c6c3a2b1afca894909a25142cc64155d8
    status: 301 